## GitLab Continuous Integration YAML file

## ------------------- used variables: ------------------- ##
  # https://gitlab.cern.ch/help/ci/variables/README.md
  # CI_COMMIT_TAG
  # CI_COMMIT_REF_NAME
  # CI_COMMIT_SHA
  # CI_MERGE_REQUEST_TARGET_BRANCH_NAME
  # CI_MERGE_REQUEST_TARGET_BRANCH_SHA
  # GITLAB_USER_EMAIL
  # GITLAB_USER_ID
  # GITLAB_USER_LOGIN
  # GITLAB_USER_NAME

## ------------------- used secure variables: ------------------- ##
  # EOS_ACCOUNT_USERNAME: Username of  to write in the EOS folder whose path is EOS_PATH
  # EOS_ACCOUNT_PASSWORD: Account password
  # KRB_PASSWORD base64 hased value
  # KRB_USERNAME base64 hased value
  # GPG_SIGNING_KEY_PRIV base64 hased value
  # GPG_PASSPHRASE base64 hased value
  # CI_DEPLOY_USER
  # CI_DEPLOY_PASSWORD

## ------------------- Stage definitions ------------------- ##
stages:
  - compile   # compile the sources, make the docs (if requested)
  - docs      # compile the docs (if requested)
  - package   # build the RPMs
  - test      # test the packages (install, run basic tests)
  - publish   # publish the RPMs and docs
  - deploy    # deploy the RPMs and docs

## ------------------- Define up anchors for various tasks, shared across all jobs utilizing them ------------------- ##
.common_variables: &common_variables
  EOS_SITE_URL:           https://cmsgemdaq.cern.ch/cmsgemdaq
  BUILD_HOME:             /builds/${CI_PROJECT_NAMESPACE}
  XDAQ_OS:                linux
  XDAQ_ROOT:              /opt/xdaq
  LD_LIBRARY_PATH:        /opt/xdaq/lib:/opt/reedmuller/lib:/opt/wiscrpcsvc/lib
  PACKAGE_NAME:           ${CI_PROJECT_NAME}
  ARTIFACTS_DIR:          artifacts
  GIT_SUBMODULE_STRATEGY: normal
  PETA_STAGE:             /data/bigdisk/sw/peta-stage
  # REPO_NAME:         ${${CI_REPOSITORY_URL##?*/}%%.*}

variables: *common_variables

## ------------------- Set up images for specified job types ------------------- #
.slc6setup: &slc6setup
  image: gitlab-registry.cern.ch/cms-gem-daq-project/gemdaq_ci_worker/extrapy/devtoolsroot:slc6

.cc7setup: &cc7setup
  image: gitlab-registry.cern.ch/cms-gem-daq-project/gemdaq_ci_worker/extrapy/devtoolsroot:cc7
  # image: gitlab-registry.cern.ch/cms-gem-daq-project/gemdaq_ci_worker/extrapy/devtoolsroot:cc7:xdaq14-6
  # image: gitlab-registry.cern.ch/cms-gem-daq-project/gemdaq_ci_worker/extrapy/devtoolsroot:cc7:xdaq15

.cc8setup: &cc8setup
  image: gitlab-registry.cern.ch/cms-gem-daq-project/gemdaq_ci_worker/extrapy/devtoolsroot:cc8
  # image: gitlab-registry.cern.ch/cms-gem-daq-project/gemdaq_ci_worker/extrapy/devtoolsroot:cc8:python2
  # image: gitlab-registry.cern.ch/cms-gem-daq-project/gemdaq_ci_worker/extrapy/devtoolsroot:cc8:python3

### ------------------- Shared setup between stages ------------------- ###
.common_setup: &common_setup |-
  mkdir -p ${ARTIFACTS_DIR}
  pip install -I --user "pip" "importlib" "codecov" "setuptools<38.2"
  sudo yum install -y wiscrpcsvc\* --enablerepo=gemos*
  sudo yum install -y reedmuller\* --enablerepo=gemos*
  source /data/bigdisk/sw/Xilinx/SDK/2016.2/settings64.sh

.retry_settings: &retry_settings
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure

.common_cache: &common_cache
  # key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
  # key: "$BUILD_ARCH"
  untracked: true
  paths:
    - ~/.cache/pip
    # - /opt/ctp7_modules
    # - /opt/reedmuller
    # - /opt/reg_utils
    # - /opt/rwreg
    # - /opt/wiscrpcsvc
    # - /opt/xhal

.common_artifacts: &common_artifacts
  name: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
  expire_in: 1d
  paths:
    - ${ARTIFACTS_DIR}

##### ------------------- Run compilation ------------------- #####
.compile_artifacts: &compile_artifacts
  untracked: true
  <<: *common_artifacts
  # paths:
  #   - ${ARTIFACTS_DIR}

.touch_compile_artifacts: &touch_compile_artifacts |-
  find ./ -type f -name '*.d' -print0 -exec touch {} \;
  find ./ -type f -name '*.o' -print0 -exec touch {} \;
  find ./ -type f -name 'lib*' -print0 -exec touch {} \;
  find ./ -type f -name 'xhalpy*' -print0 -exec touch {} \;
  # find ./python/reg_interface_gem/pkg/xhal -type f -print0 -exec touch {} \;

.before_compile: &before_compile
  ## these are set in the Dockerfile, but don't work in the gitlab CI by default?
  - export BUILD_HOME=/builds/$CI_PROJECT_NAMESPACE
  - export ARTIFACTS_DIR=$BUILD_HOME/artifacts
  - *common_setup

.compile_common: &compile_common
  only:
    - /^issue.*$/
    - /^hotfix.*$/
    - /^release.*$/
    - /^feature.*$/
    - /^citest.*$/
    - develop
    - master
    - tags
  tags:
  stage: compile
  before_script:
    *before_compile
  script:
    - make all -j8
    # - mkdir ${ARTIFACTS_DIR}/${XDAQ_PLATFORM}
    # - find . -iname '*.so' -print0 -exec mv -t ${ARTIFACTS_DIR}/${XDAQ_PLATFORM} {} \+
  after_script:
    - ls -la ${ARTIFACTS_DIR}
  artifacts:
    name: ${CI_JOB_STAGE}
    <<: *compile_artifacts

compile:cc7:
  <<: *cc7setup
  <<: *compile_common
  environment:
  variables:
  cache:

# compile:cc8:
#   <<: *cc8setup
#   <<: *compile_common
#   environment:
#   variables:
#   cache:

##### ------------------- Generate docs ------------------- #####
.docs_artifacts: &docs_artifacts
  untracked: true
  <<: *common_artifacts
  # paths:
  #   - ${ARTIFACTS_DIR}
  #   - doc/build/html

.touch_docs_artifacts: &touch_docs_artifacts |-
  find ./python/reg_interface_gem/doc/_build -type f -print0 -exec touch {} \;
  # find ./doc/html -type f -print0 -exec touch {} \;
  # find ./doc/latex -type f -print0 -exec touch {} \;

# generate docs
docs:
  <<: *cc7setup
  stage: compile
  only:
    - /^feature.*ci-cd*$/
    - /^citest.*$/
    - /^develop$/
    - /^release.*$/
    - tags
    - master
  dependencies:
  before_script:
    - eval `set | egrep '^(CI|GIT)' | awk -F= '{ print "export " $1 }'`
    - eval `set | egrep '^(BUILD|REL|PACK|ARTI|XDAQ|CMS|LD)' | awk -F= '{ print "export " $1 }'`
  script:
    - make doc
    # - doxygen -s ${BUILD_HOME}/doc/cmsgemos.cfg >& /dev/null
  after_script:
    - |
      mkdir -p ${ARTIFACTS_DIR}/api
      mv -t ${ARTIFACTS_DIR}/api/ doc/build/html/*
  artifacts:
    name: ${CI_JOB_STAGE}
    <<: *docs_artifacts
  coverage: '/Documentation coverage: \d+\.\d+/'

##### ------------------- Run tests using the compiled binaries ------------------- #####
.before_test: &before_test
  - eval `set | egrep '^(CI|GIT)' | awk -F= '{ print "export " $1 }'`
  - eval `set | egrep '^(BUILD|REL|PACK|ARTI|XDAQ|CMS|LD)' | awk -F= '{ print "export " $1 }'`
  - |
    sudo yum install -y wiscrpcsvc\* --enablerepo=gemos*
    sudo yum install -y reedmuller\* --enablerepo=gemos*

# run tests using the binary built before
test:cc7:
  <<: *cc7setup
  stage: test
  dependencies:
    - compile:cc7
  before_script:
    *before_test
  script:
    - echo ./runmytests.sh
  after_script:
    - 'echo "FIXME: parse-abi-changes.sh"'
    - 'echo "FIXME: test summary"'
  coverage: '/Test coverage: \d+\.\d+/'

# test:cc8:
#   <<: *cc8setup
#   stage: test
#   dependencies:
#     - compile:cc8
#   before_script:
#     *before_test
#   script:
#     - echo ./runmytests.sh
#   after_script:
#     - 'echo "FIXME: parse-abi-changes.sh"'
#     - 'echo "FIXME: test summary"'
#   coverage: '/Test coverage: \d+\.\d+/'

##### ------------------- Package generated files into RPMs and tarballs ------------------- #####
.package_artifacts: &package_artifacts
  untracked: true
  <<: *common_artifacts
  # paths:
  #   - ${ARTIFACTS_DIR}

.touch_package_artifacts: &touch_package_artifacts |-
  find ./python/reg_interface_gem/pkg/xhal -type f -print0 -exec touch {} \;
  find ./python/reg_interface_gem/rpm -type f -iname 'setup.py' -print0 -exec touch {} \;
  find ./python/reg_interface_gem/rpm -type f -iname 'reg_interface_gem.src.rpm' -print0 -exec touch {} \;
  find ./python/reg_interface_gem/rpm -type f -iname 'reg_interface_gem.x86_64.rpm' -print0 -exec touch {} \;
  find ./python/reg_interface_gem/rpm -type f -iname 'reg_interface_gem.zip' -print0 -exec touch {} \;
  find ./xhal*/rpm -type f -wholename '*/rpm/xhal*.tbz2' -print0 -exec touch {} \;
  find ./xhal*/rpm -type f -wholename '*/rpm/xhal.spec' -print0 -exec touch {} \;
  find ./xhal*/rpm -type f -wholename '*/rpm/xhal*.src.rpm' -print0 -exec touch {} \;
  find ./xhal*/rpm -type f -wholename '*/rpm/xhal*.arm*.rpm' -print0 -exec touch {} \;
  find ./xhal*/rpm -type f -wholename '*/rpm/xhal*.x86_64.rpm' -print0 -exec touch {} \;

.before_package: &before_package |-
  eval `set | egrep '^(CI|GIT)' | awk -F= '{ print "export " $1 }'`
  eval `set | egrep '^(BUILD|REL|PACK|ARTI|XDAQ|CMS|LD)' | awk -F= '{ print "export " $1 }'`

.package_common: &package_common
  stage: package
  before_script:
    - *common_setup
    - *before_package
  script:
    ## Ensure compile artifacts are more recent than the checkout
    - *touch_compile_artifacts
    - *touch_docs_artifacts
    - make rpm
    ## Move packaged files to deployment staging area
    - eval `set | egrep '^(CI|GIT)' | awk -F= '{ print "export " $1 }'`
    - eval `set | egrep '^(EOS|BUILD|REL|PACK|ARTI|XDAQ|CMS|LD)' | awk -F= '{ print "export " $1 }'`
  after_script:
#    - mv repos ${ARTIFACTS_DIR}
    - ls -la ${ARTIFACTS_DIR}
    - ls -la ${ARTIFACTS_DIR}/repos
  artifacts:
    name: ${CI_JOB_STAGE}
    <<: *package_artifacts

# generate RPMs
package:cc7:unstable:
  <<: *cc7setup
  only:
    - /^develop$/
    - /^feature.*ci-cd*$/
    - /^citest.*$/
    # - triggers            ## should go into releases/'testing' or unstable?
    # - chat                ## should go into releases/'testing' or unstable?
    # - api                 ## should go into releases/'testing' or unstable?
  tags:
  variables:
    COMPILER: 'gcc'
    PYEXE: 'python2.7'
    PACKAGE_TYPE: 'unstable'
  dependencies:
    - compile:cc7
    - docs
  <<: *package_common

package:cc7:testing:
  <<: *cc7setup
  only:
    - /^release.*$/
  tags:
  variables:
    COMPILER: 'gcc'
    PYEXE: 'python2.7'
    PACKAGE_TYPE: 'testing'
  dependencies:
    - compile:cc7
    - docs
  <<: *package_common

package:cc7:base:
  <<: *cc7setup
  only:
    - tags
  tags:
  variables:
    COMPILER: 'gcc'
    PYEXE: 'python2.7'
    PACKAGE_TYPE: 'base'
  dependencies:
    - compile:cc7
    - docs
  <<: *package_common

# package:cc8:
#   <<: *cc8setup
#   dependencies:
#     - compile:cc8
#     - docs
#   <<: *package_common

##### ------------------- Publish RPMs, docs, and tarballs ------------------- #####
.publish_variables: &publish_variables
  EOS_BASE_WEB_DIR:   "/eos/project/c/cmsgemdaq/www/ci-test"
  EOS_COMMON_WEB_DIR: "cmsgemdaq"
  EOS_DOC_NAME:       "api"
  EOS_REPO_NAME:      "repos"
  EOS_SITE_WEB_DIR:   "${EOS_BASE_WEB_DIR}/${CI_PROJECT_NAME}"
  EOS_SW_DIR:         "sw/${CI_PROJECT_NAME}"
  EOS_DOCS_DIR:       "docs/${CI_PROJECT_NAME}"
  EOS_UNSTABLE_DIR:   "unstable"
  EOS_RELEASE_DIR:    "releases"

.publish_common: &publish_common
  <<: *cc7setup
  stage: publish
  variables: *publish_variables
  before_script:
    - eval `set | egrep '^(KRB|CI|GIT)' | awk -F= '{ print "export " $1 }'`
    - eval `set | egrep '^(EOS|BUILD|REL|PACK|ARTI|XDAQ|CMS|LD)' | awk -F= '{ print "export " $1 }'`
    - *common_setup
    - sudo yum install -y rpm-sign
  script:
    # - push python packages to pypi/conda
    # - push RPMs to packagecloud.io
    # - push RPMs to gitlab yum repo, a la xDAQ?
    # - push sphinx/rst/md/rtd docs to readthedocs.io
    # - push sphinx/rst/md/rtd docs to $EOS_WEB_DIR/docs/${fulltag}, update doc main page index
    - 'echo "FIXME: github_changelog_generator"'
    - 'echo "FIXME: cp CHANGELOG.md ${ARTIFACTS_DIR}"'
    - *touch_compile_artifacts
    - *touch_docs_artifacts
    - *touch_package_artifacts
    - make release
    - cp -rfp release/* ${ARTIFACTS_DIR}
    - ${BUILD_HOME}/${CI_PROJECT_NAME}/config/ci/publish_eos.sh
    - if [ -n "${DEBUG_CI}" ]; then sleep 500; fi

# publish:debug:
#   variables:
#     EOS_BASE_WEB_DIR: /tmp/
#   <<: *publish_common
#   variables:
#     DEBUG_CI: 'yes'
#   only:
#     - /^citest.*$/
#   when: manual
#   after_script:

publish:unstable:
  variables:
    EOS_BASE_WEB_DIR: /tmp/
  <<: *publish_common
  only:
    - /^feature.*ci-cd*$/
    - /^citest.*$/
    - /^develop$/
  dependencies:
    - package:cc7:unstable
  after_script:
    - ls -la ${ARTIFACTS_DIR}

publish:testing:
  <<: *publish_common
  only:
    - /^release.*$/
  dependencies:
    - package:cc7:testing
  after_script:
    # - notify mattermost
    # - send email
    # - generate_release.sh pre

publish:base:
  <<: *publish_common
  only:
    - tags
  dependencies:
    - package:cc7:base
  after_script:
    - 'echo "FIXME: github_changelog_generator"'
    - 'echo "FIXME: generate_release_notes.sh"'
    # - notify mattermost
    # - send email
    # - generate_release.sh rel
